apiVersion: v1
kind: Secret
metadata:
  name: ingest-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "your-username"
  SPRING_DATASOURCE_PASSWORD: "your-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: processing-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "your-username"
  SPRING_DATASOURCE_PASSWORD: "your-password"
  PROCESSING_CLIENT_SECRET: "YOUR_PROCESSING_CLIENT_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: report-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "your-username"
  SPRING_DATASOURCE_PASSWORD: "your-password"
