events {}

http {
    upstream ingest {
        server ingest-service:8081;
    }

    upstream reports {
        server report-service:8083;
    }

    server {
        listen 80;

        location /api/v1/uploads {
            proxy_pass http://ingest;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            client_max_body_size 10M;
        }

        location /api/v1/reports {
            proxy_pass http://reports;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            return 200 '{"status":"UP"}';
            add_header Content-Type application/json;
        }
    }
}