events {}

http {
    server {
        listen 80;

        location /api/v1/uploads {
            resolver 127.0.0.11 valid=30s;
            set $ingest http://ingest-service:8081;
            proxy_pass $ingest;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            client_max_body_size 10M;
        }

        location /api/v1/reports {
            resolver 127.0.0.11 valid=30s;
            set $reports http://report-service:8083;
            proxy_pass $reports;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /realms/ {
            resolver 127.0.0.11 valid=30s;
            set $keycloak http://keycloak:8080;
            proxy_pass $keycloak;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            return 200 '{"status":"UP"}';
            add_header Content-Type application/json;
        }
    }
}