apiVersion: v1
kind: ConfigMap
metadata:
  name: processing-service-config
data:
  SERVER_PORT: "8082"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/processing_service"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  INGEST_BASE_URL: "http://ingest-service:8081"
  OAUTH2_TOKEN_URI: "http://keycloak:8180/realms/microservices-realm/protocol/openid-connect/token"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-service
  labels:
    app: processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing-service
  template:
    metadata:
      labels:
        app: processing-service
    spec:
      containers:
        - name: processing-service
          image: files-pipeline-processing-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: processing-service-config
            - secretRef:
                name: processing-service-secret
          env:
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx192m -XX:+UseG1GC -XX:MaxGCPauseMillis=100"
          resources:
            requests:
              memory: "384Mi"
              cpu: "100m"
            limits:
              memory: "384Mi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: processing-service
spec:
  type: ClusterIP
  selector:
    app: processing-service
  ports:
    - port: 8082
      targetPort: 8082