server:
  port: 9000

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8180/realms/microservices-realm

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ingest-service
              uri: http://ingest-service:8081
              predicates:
                - Path=/api/v1/uploads/**
                - Method=POST,GET
              filters:
                - PreserveHostHeader
                - name: RequestSize
                  args:
                    maxSize: 10MB
            - id: report-service
              uri: http://report-service:8083
              predicates:
                - Path=/api/v1/reports/**
                - Method=GET
              filters:
                - PreserveHostHeader

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      access: read-only

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
#    reactor.netty.http.client: DEBUG